kafka:
  simple-topic: 'simple-topic'
  reply-topic: 'reply-topic'
  sent-to-topic: 'sent-to-topic'
  specific-topic: 'specific-topic'

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: poc-group